name: pegasus_x_ryuichi
description: Pegasus-X

publish_to: 'none'
version: 21.1.0+2110

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  device_info_plus: ^9.1.2
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  webview_flutter: ^4.10.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  shimmer: ^3.0.0
  video_player: ^2.8.3
  fluttertoast: ^8.2.4
  audioplayers: ^6.0.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  permission_handler: ^11.3.0
  file_picker: ^8.0.0
  flutter_local_notifications: ^17.2.0
  
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/video/
    - assets/sound/
    - assets/settings.json
    - icon.jpg
  
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
    - family: ShareTechMono
      fonts:
        - asset: assets/fonts/ShareTechMono-Regular.ttf
    - family: Deltha
      fonts:
        - asset: assets/fonts/Deltha.ttf
