import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppLocalizations extends ChangeNotifier {
  static AppLocalizations _instance = AppLocalizations._();
  factory AppLocalizations() => _instance;
  AppLocalizations._();

  static AppLocalizations get instance => _instance;

  String _lang = 'id';
  String get lang => _lang;

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _lang = prefs.getString('app_lang') ?? 'id';
    notifyListeners();
  }

  Future<void> setLang(String lang) async {
    _lang = lang;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_lang', lang);
    notifyListeners();
  }

  String t(String key) => _texts[_lang]?[key] ?? _texts['id']![key] ?? key;

  static final Map<String, Map<String, String>> _texts = {
    'id': {
      // Dashboard
      'app_title': 'PEGASUS-X 2K26',
      'logout': 'Keluar',
      'logout_confirm': 'Yakin Ingin Keluar?',
      'cancel': 'Batal',
      'settings': 'Pengaturan',
      'chat': 'Chat',
      'cart': 'Keranjang',
      'menu': 'Menu',
      'contact_owner': 'Hubungi Owner',
      // Home
      'information_account': 'INFORMASI AKUN',
      'management_app': 'MANAGEMENT APP',
      'manage_sender': 'Kelola Sender',
      'manage_users': 'Kelola User',
      'online_users': 'Pengguna Online',
      'connections': 'Koneksi',
      'overlay': 'Overlay',
      'overlay_active': 'Overlay Aktif! Keluar Aplikasi Untuk Lihat Tombol Floating.',
      'overlay_disabled': 'Overlay Dimatikan.',
      'overlay_permission': 'Permission Overlay Belum Diberikan. Buka Setting Dan Izinkan "Display Over Other Apps".',
      // Profile Settings
      'profile_settings': 'Pengaturan Profil',
      'username': 'Username',
      'password': 'Password',
      'role': 'Role',
      'change_password': 'Ganti Password',
      'old_password': 'Password Lama',
      'new_password': 'Password Baru',
      'confirm_password': 'Konfirmasi Password',
      'save': 'Simpan',
      'change_photo': 'Ganti Foto',
      'app_language': 'Bahasa Aplikasi',
      'indonesian': 'Bahasa Indonesia',
      'english': 'Bahasa Inggris',
      'password_changed': 'Password Berhasil Diubah',
      'password_wrong': 'Password Lama Salah',
      'password_mismatch': 'Password Baru Tidak Cocok',
      'avatar_updated': 'Foto Profil Berhasil Diperbarui',
      // General
      'close': 'Tutup',
      'loading': 'Memuat...',
      'error': 'Terjadi Kesalahan',
      'success': 'Berhasil',
      'confirm': 'Konfirmasi',
      // Manage Users
      'search_user': 'Cari Username / ID Telegram',
      'ban_user': 'Ban User',
      'unban_user': 'Unban User',
      'banned': 'Dibanned',
      'active': 'Aktif',
      'ban_reason': 'Alasan Ban',
      'ban_confirm': 'Yakin Ingin Ban User Ini?',
      'user_banned': 'User Berhasil Dibanned',
      'user_unbanned': 'User Berhasil Di-Unban',
      // Donate
      'donate_title': 'Donasi Seikhlasnya',
      'donate_body': 'Hei! Pegasus-X Revenge terus berkembang berkat dukungan kalian.\nScan QRIS di bawah untuk berdonasi seikhlasnya.\nSetiap donasi sangat berarti untuk pengembangan aplikasi ini.',
      // Contact Owner
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'tiktok': 'TikTok',
      'github': 'GitHub',

      // Chat List
      'no_other_users': 'Belum ada user lain.',
      'group_label': 'GRUP',
      'msg_screen_title': 'PESAN',
      // Chat Screen
      'no_messages': 'Belum Ada Pesan',
      'send_first': 'Kirim Pesan Pertama!',
      'owner_label': 'Owner',
      'reply_to': 'Balas',
      'reply_label': 'Membalas',
      'delete_msg': 'Hapus',
      'hacked_title': 'HACKED',
      'tab_device_connect': 'CONNECT',
      'tab_hack_command': 'COMMAND',
      'coming_soon': 'Fitur Coming Soon',
      'coming_soon_body': 'Fitur ini sedang dalam pengembangan.\nNantikan update selanjutnya!',
      'lock_device': 'Lock Device',
      'unlock_device': 'Unlock Device',
      'hack_flashlight': 'Hack Senter',
      'hack_wallpaper': 'Hack Wallpaper',
      'view_gallery': 'View Gallery',
      'spyware_sms': 'Spyware SMS',
      'vibrate_device': 'Getarkan Device',
      'take_photo': 'Take Photo',
      'delete_file': 'Delete File',
      'get_location': 'Get Location',
      'lock_text_hint': 'Teks Yang Tampil Di Layar Target:',
      'pin_unlock': 'Pin Untuk Unlock:',
      'lock_btn': 'Kunci',
      'select_device_first': 'Pilih Device Dulu Untuk Mengirim Command',
      'no_access': 'Akses Ditolak',
      'vip_only': 'Hanya VIP dan Owner Yang Bisa\nMengakses Fitur Ini',
      'no_device_online': 'Tidak Ada Device Online',
      'device_hint': 'Pastikan Pegasus-X Fearless Sudah\nBerjalan Di Device Target',
      'select_device': 'Pilih Device Target',
      'hacked_commands': 'Hacked Commands',
      // Manage Tab
      'add_sender': 'TAMBAH SENDER',
      'add_sender_title': 'TAMBAH SENDER',
      'phone_hint': 'Masukkan Nomor WhatsApp (Format: 628xxxxxxxx)',
      'get_code': 'Dapatkan Kode',
      'delete_sender_title': 'Hapus Sender',
      'delete_sender_confirm': 'Hapus Sender',
      'manage_sender_title': 'MANAGE SENDER',
      'manage_sender_sub': 'Kelola Sender WhatsApp Kamu',
      'sender_online': 'Online',
      'sender_total': 'Total',
      'sender_offline': 'Offline',
      'sender_connected': 'Sender Terhubung',
      'pairing_code': 'Pairing Code',
      'pairing_enter': 'Masukkan Kode Ini Di WhatsApp',
      'pairing_valid': 'Kode Berlaku Beberapa Menit',
      'pairing_cancel': 'Batalkan',
      'no_sender': 'Belum Ada Sender',
      'add_sender_hint': 'Tap "Tambah Sender" Untuk Menghubungkan\nNomor WhatsApp Kamu',
      'sender_terhubung': 'Terhubung',
      'sender_terputus': 'Terputus',
      'connecting': 'Menghubungkan...',
      'pick_sender': 'Pilih Sender',
      'pick_sender_sub': 'Pilih Nomer WhatsApp Sebagai Pengirim',
      'no_sender_connected': 'Belum Ada Sender Terhubung.\nTambahkan Sender Di Tab Manage.',
      'bug_wa': 'BUG WHATSAPP',
      // Manage Users Screen
      'ban_delete_user': 'BAN & HAPUS USER',
      'ban_delete_btn': 'BAN & HAPUS',
      'manage_users_title': 'MANAGE USERS',
      'no_user': 'Tidak ada user.',
      'no_banned': 'Tidak ada username yang dibanned.',      
      'delete_session': 'Hapus Session',
      'pick_user': 'Pilih User',
      'move_sender': 'Pindah',
      'take_sender': 'Ambil',
      'no_sender_registered': 'Belum Ada Sender Terdaftar',      
      'wa_call_title': 'WHATSAPP CALL',
      'no_sender_online': 'Tidak Ada Sender Online',
      'spam_ngl_title': 'SPAM NGL',
      'spam_pairing_title': 'SPAM PAIRING',
      'remini_title': 'REMINI AI',
      'tap_pick_photo': 'Tap Untuk Pilih Foto',
      'change_photo_btn': 'Ganti Foto',
      'processing': 'Memproses...',
      'enhance_photo': 'ENHANCE FOTO',
      'failed_load_result': 'Gagal Memuat Hasil',      
      'iqc_title': 'IPHONE QUOTE',
      'generating': 'Generating...',
      'generate_quote': 'GENERATE QUOTE',
      'failed_load_image': 'Gagal Memuat Gambar',
      'change_password_title': 'Ganti Password',
      'account_security': 'Keamanan Akun',
      'update_password_hint': 'Perbarui Password Untuk Keamanan Akun',
      'save_changes': 'SIMPAN PERUBAHAN',      
      'downloader_title': 'DOWNLOADER',
      'fetching_data': 'Mengambil Data...',
      'fetch_data': 'Ambil Data',
      'tools_title': 'TOOLS DASHBOARD',
      'login_secure': '[ Secure Login ]',
      'login_btn': 'Masuk',
      'register_btn': 'Registrasi',      
      'ddos_title': 'DDOS TOOL',
      'multi_layer': 'MULTI LAYER',
      'cooldown_active': 'COOLDOWN AKTIF',
      'cooldown_warning': 'Multi Layer Tidak Bisa Digunakan Saat Cooldown.',
      'pick_layer': 'Pilih Layer Method...',
      'cooldown_duration': 'Durasi Cooldown',
      'attack_duration': 'Durasi Attack',
      'access_limited': 'AKSES TERBATAS',      
      'new_message': 'Pesan Baru',
      'new_chat_notif': 'Ada pesan baru di chat',
    },
    'en': {
      // Dashboard
      'app_title': 'PEGASUS-X 2K26',
      'logout': 'Logout',
      'logout_confirm': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'settings': 'Settings',
      'chat': 'Chat',
      'cart': 'Cart',
      'menu': 'Menu',
      'contact_owner': 'Contact Owner',
      // Home
      'information_account': 'ACCOUNT INFORMATION',
      'management_app': 'MANAGEMENT APP',
      'manage_sender': 'Manage Sender',
      'manage_users': 'Manage Users',
      'online_users': 'Online Users',
      'connections': 'Connections',
      'overlay': 'Overlay',
      'overlay_active': 'Overlay Active! Exit the app to see the floating button.',
      'overlay_disabled': 'Overlay Disabled.',
      'overlay_permission': 'Overlay Permission Not Granted. Go to Settings and allow "Display Over Other Apps".',
      // Profile Settings
      'profile_settings': 'Profile Settings',
      'username': 'Username',
      'password': 'Password',
      'role': 'Role',
      'change_password': 'Change Password',
      'old_password': 'Old Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'save': 'Save',
      'change_photo': 'Change Photo',
      'app_language': 'App Language',
      'indonesian': 'Indonesian',
      'english': 'English',
      'password_changed': 'Password Changed Successfully',
      'password_wrong': 'Old Password is Wrong',
      'password_mismatch': 'New Passwords Do Not Match',
      'avatar_updated': 'Profile Photo Updated Successfully',
      // General
      'close': 'Close',
      'loading': 'Loading...',
      'error': 'An Error Occurred',
      'success': 'Success',
      'confirm': 'Confirm',
      // Manage Users
      'search_user': 'Search Username / Telegram ID',
      'ban_user': 'Ban User',
      'unban_user': 'Unban User',
      'banned': 'Banned',
      'active': 'Active',
      'ban_reason': 'Ban Reason',
      'ban_confirm': 'Are you sure you want to ban this user?',
      'user_banned': 'User Banned Successfully',
      'user_unbanned': 'User Unbanned Successfully',
      // Donate
      'donate_title': 'Voluntary Donation',
      'donate_body': 'Hey! Pegasus-X Revenge keeps growing thanks to your support.\nScan the QRIS below to donate any amount.\nEvery donation means a lot for the development of this app.',
      // Contact Owner
      'whatsapp': 'WhatsApp',
      'instagram': 'Instagram',
      'tiktok': 'TikTok',
      'github': 'GitHub',

      // Chat List
      'no_other_users': 'No other users yet.',
      'group_label': 'GROUP',
      'msg_screen_title': 'MESSAGES',
      // Chat Screen
      'no_messages': 'No Messages Yet',
      'send_first': 'Send the First Message!',
      'owner_label': 'Owner',
      'reply_to': 'Reply',
      'reply_label': 'Replying to',
      'delete_msg': 'Delete',
      // Hacked Screen
      'hacked_title': 'HACKED',
      'tab_device_connect': 'DEVICE CONNECT',
      'tab_hack_command': 'HACK COMMAND',
      'coming_soon': 'Coming Soon',
      'coming_soon_body': 'This feature is under development.\nStay tuned for the next update!',
      'lock_device': 'Lock Device',
      'unlock_device': 'Unlock Device',
      'hack_flashlight': 'Hack Flashlight',
      'hack_wallpaper': 'Hack Wallpaper',
      'view_gallery': 'View Gallery',
      'spyware_sms': 'Spyware SMS',
      'vibrate_device': 'Vibrate Device',
      'take_photo': 'Take Photo',
      'delete_file': 'Delete File',
      'get_location': 'Get Location',
      'lock_text_hint': 'Text Shown On Target Screen:',
      'pin_unlock': 'PIN To Unlock:',
      'lock_btn': 'Lock',
      'select_device_first': 'Select a Device First to Send Command',
      'no_access': 'Access Denied',
      'vip_only': 'Only VIP and Owner Can\nAccess This Feature',
      'no_device_online': 'No Device Online',
      'device_hint': 'Make Sure Pegasus-X Fearless Is\nRunning On The Target Device',
      'select_device': 'Select Target Device',
      'hacked_commands': 'Hacked Commands',
      // Manage Tab
      'add_sender': 'Add Sender',
      'add_sender_title': 'ADD SENDER',
      'phone_hint': 'Enter WhatsApp Number (Format: 628xxxxxxxx)',
      'get_code': 'Get Code',
      'delete_sender_title': 'Delete Sender',
      'delete_sender_confirm': 'Delete Sender',
      'manage_sender_title': 'MANAGE SENDER',
      'manage_sender_sub': 'Manage Your WhatsApp Sender',
      'sender_online': 'Online',
      'sender_total': 'Total',
      'sender_offline': 'Offline',
      'sender_connected': 'Sender Connected',
      'pairing_code': 'Pairing Code',
      'pairing_enter': 'Enter This Code In WhatsApp',
      'pairing_valid': 'Code Valid for a Few Minutes',
      'pairing_cancel': 'Cancel',
      'no_sender': 'No Sender Yet',
      'add_sender_hint': 'Tap "Add Sender" To Connect\nYour WhatsApp Number',
      'sender_terhubung': 'Connected',
      'sender_terputus': 'Disconnected',
      'connecting': 'Connecting...',
      // Bug Tab
      'pick_sender': 'Pick Sender',
      'pick_sender_sub': 'Pick WhatsApp Number as Sender',
      'no_sender_connected': 'No Sender Connected.\nAdd a Sender in the Manage Tab.',
      'bug_wa': 'BUG WHATSAPP',
      // Manage Users Screen
      'ban_delete_user': 'BAN & DELETE USER',
      'ban_delete_btn': 'BAN & DELETE',
      'manage_users_title': 'MANAGE USERS',
      'no_user': 'No users.',
      'no_banned': 'No banned usernames.',
      // Owner Management
      'delete_session': 'Delete Session',
      'pick_user': 'Pick User',
      'move_sender': 'Move',
      'take_sender': 'Take',
      'no_sender_registered': 'No Sender Registered',
      // WA Call Screen
      'wa_call_title': 'WHATSAPP CALL',
      'no_sender_online': 'No Sender Online',
      // Spam NGL
      'spam_ngl_title': 'SPAM NGL',
      // Spam Pairing
      'spam_pairing_title': 'SPAM PAIRING',
      // Remini
      'remini_title': 'REMINI AI',
      'tap_pick_photo': 'Tap To Pick Photo',
      'change_photo_btn': 'Change Photo',
      'processing': 'Processing...',
      'enhance_photo': 'ENHANCE PHOTO',
      'failed_load_result': 'Failed to Load Result',
      // IQC
      'iqc_title': 'IPHONE QUOTE',
      'generating': 'Generating...',
      'generate_quote': 'GENERATE QUOTE',
      'failed_load_image': 'Failed to Load Image',
      // Change Password
      'change_password_title': 'Change Password',
      'account_security': 'Account Security',
      'update_password_hint': 'Update Password for Account Security',
      'save_changes': 'SAVE CHANGES',
      // Downloader
      'downloader_title': 'DOWNLOADER',
      'fetching_data': 'Fetching Data...',
      'fetch_data': 'Fetch Data',
      // Tools Tab
      'tools_title': 'TOOLS DASHBOARD',
      // Login
      'login_secure': '[ Secure Login ]',
      'login_btn': 'Login',
      'register_btn': 'Register',
      // DDOS
      'ddos_title': 'DDOS TOOL',
      'multi_layer': 'MULTI LAYER',
      'cooldown_active': 'COOLDOWN ACTIVE',
      'cooldown_warning': 'Multi Layer Cannot Be Used During Cooldown.',
      'pick_layer': 'Pick Layer Method...',
      'cooldown_duration': 'Cooldown Duration',
      'attack_duration': 'Attack Duration',
      'access_limited': 'ACCESS LIMITED',
      // Notification
      'new_message': 'New Message',
      'new_chat_notif': 'There is a new message in chat',
    },
  };
}

String tr(String key) => AppLocalizations.instance.t(key);
